### ISSUE TITLE
Tags warning

### ISSUE THREAD

**Issue by mbrsolution** [sayontan/suffusion#13]
Hi Drake, how are you?

This is not a major issue. So take your time to fix this. This is more for consistency.

WARNING: The tag white has been deprecated, please remove it from your style.css header.
WARNING: The tag silver has been deprecated, please remove it from your style.css header.
WARNING: The tag responsive-layout has been deprecated, please remove it from your style.css header.
WARNING: The tag red has been deprecated, please remove it from your style.css header.
WARNING: The tag purple has been deprecated, please remove it from your style.css header.
WARNING: The tag photoblogging has been deprecated, please remove it from your style.css header.
WARNING: The tag orange has been deprecated, please remove it from your style.css header.
WARNING: The tag light has been deprecated, please remove it from your style.css header.
WARNING: The tag green has been deprecated, please remove it from your style.css header.
WARNING: The tag fluid-layout has been deprecated, please remove it from your style.css header.
WARNING: The tag fixed-layout has been deprecated, please remove it from your style.css header.
WARNING: The tag dark has been deprecated, please remove it from your style.css header.
WARNING: The tag blue has been deprecated, please remove it from your style.css header.
WARNING: The tag blavatar has been deprecated, please remove it from your style.css header.
WARNING: The tag black has been deprecated, please remove it from your style.css header.

And one more 

REQUIRED: Text Domain: is missing from your style.css header.

Here is the link for your perusal.

https://make.wordpress.org/themes/2016/05/24/new-theme-tags-have-arrived/

Thank you

**Comment by Ciprian-Dracea** [comment]
Hi,

Sometime eventually I will remove those tags wich don't affect anything. They are just comments in style.css. The deprecation wasn't triggered by better versions of php, css, html or javascript. Is triggered by theme reviewers who's don't have anything to do but just invent problems. Next meeting they will find anything else, I'm pretty confident...

But hey... We don't care, the theme isn't in repository anymore, no one can find the theme there looking for any tag....

Thank you for the report, I will change those lines as soon as possible, mostly because really they don't mean anything now...
