### ISSUE TITLE
Delete title in head-section

### ISSUE THREAD

**Issue by Schimmelreiter2019** [sayontan/suffusion#3]
Hello, I'm using the TNG(Genealogy)-Wordpress-Plugin within suffusion-theme. In wordpress I have  only one page (called "stammbaum"), which is the base for all the different pedigrees generated by TNG.
The problem is, that each pedigree-page has the same title in the browser (depending on the page-name), because wordpress writes its own title in the head, BEFORE the right TNG-title, and the browser seems to accept only the first title-tag.
Here is an example of one page: [http://www.der-familienstammbaum.de/stammbaum/pedigree.php?personID=I44&tree=Stammbaum](url)
(In the screenshot below you'll find in the source-code both titles.)
In my opinion, there is only one way to solve this: to delete the first wordpress-title. But how can I do that? Where do I find the code, I have to modify?
Usually I do those things with the Yoast-SEO-Plugin, but with this theme I don't know what to do.
Thank you very much in advance for your help :-)
![screenshot](https://user-images.githubusercontent.com/49270841/55544163-cb8e6480-56ca-11e9-8215-85da02f165c5.jpg)

**Comment by mbrsolution** [comment]
Hi, I don't know anything about the plugin you mentioned. And I don't think this has anything to do with the permalink settings in WordPress. However I am wondering if this problem is more related to the plugin in question. Do you know if there is any settings in the plugin that allows you to manage the titles? Have you asked the developers of this plugin how to manage the titles as per your question above? 

Kind regards

**Comment by Schimmelreiter2019** [comment]
Thanks for your reply :-)
Unfortunately there are no settings in the plugin-admin, which could solve the problem. I already asked the developer Darrin Lythgoe, but he couldn't help me. So it seem's, that I have to modify somehow the head of the pages. Do you know, where suffusion handles the generation of the title, so that I could modify the code (e.g. with Yoast SEO plugin)?

**Comment by Ciprian-Dracea** [comment]
You can have only one <title> tag on a page since the beginning of internet. Two title tags printed in 
<head> section is not valid html and the browsers get only one title,

Suffusion use standard WordPress functions, i.e. wp_head(), to generate the html meta-tags. Also the theme is using add_theme_support('title-tag'); which instruct the theme to use whatever title tag is generated by WordPress or other plugins (like Yoast or All in One SEO which always works with Suffusion).

To see where the tags are generated can open header.php from "suffusion" folder. It is a pluggable file, you can edit the file in a child theme to get other result. But I strongly recommend to NOT DO THAT.
Most probably will ruin all other tags/styles/scripts which are loaded by "wp_head()" in header.

So, as the title tag is generated by WordPress functions, this can be overwritten with the right filters added by plugins. I don't know your particular plugin, but probably should try to use "wp_title" filter ([https://developer.wordpress.org/reference/hooks/wp_title/]), or, if is already using it, could try to increase the priority of the filter.

**Comment by Schimmelreiter2019** [comment]
Thanks a lot! I already checked the header.php, but couldn't change anything there. I'll try it with the "wp_title"-filter  ;-)

**Comment by RogerKIWI** [comment]
I have a TNG Mod Manager .cfg file that can change the needed code in WordPress to let the TNG title show on your Genealogy page. I tried to post the code here but it won't let me for some reason - you can go to 

http://lisaandroger.com/downloads/download-info/page-title-change-for-tng-and-wordpress/

and download the .cfg file from there.

Roger

**Comment by Schimmelreiter2019** [comment]
Hi Roger,
thank you very much for your message! I've tried to install the mod-file,
but the installation failed. Your file-version is 10.0.0.0, but my TNG has
version 11.0.1. This seems to be the problem. Do you have a newer version
of the file?

Thank you very much in advanced
Andreas

Am Di., 23. Apr. 2019 um 02:52 Uhr schrieb Roger Moffat <
notifications@github.com>:

**Comment by RogerKIWI** [comment]
Version 10.0.0.0 is the only version of this that I have created - it works from TNG 10.0 through to TNG 12.1 - since it is modifying a WordPress file, not a TNG file, the TNG version is irrelevant.

Check the file that you downloaded from my site to make sure that the path in it are correct - you may need to alter the line

`%target:../wp/wp-includes/general-template.php%`

depending on what your WordPress folder is called (the "wp" in the above), and its path relative to your TNG installation.

Roger

**Comment by Schimmelreiter2019** [comment]
Aaah, ok, I'll try it.  :-)

Roger Moffat <notifications@github.com> schrieb am Mi., 24. Apr. 2019 15:36:

**Comment by Schimmelreiter2019** [comment]
Hi Roger,
it works, thank you very much  :-D
Kind regards
Andreas

Am Mi., 24. Apr. 2019 um 15:36 Uhr schrieb Roger Moffat <
notifications@github.com>:

**Comment by mbrsolution** [comment]
Hi, if your issue is resolved can you close it.

Thank you
