### ISSUE TITLE
Possible obsolete filter

### ISSUE THREAD

**Issue by mbrsolution** [sayontan/suffusion#75]
Hi Marc, when you have some spare time. You might like to investigate the following filter found in line 227 inside the file **_"functions.php"_**

`add_filter('user_contactmethods', 'suffusion_add_user_contact_methods');`

I can't find any more refences in the theme's directory regarding the above filter other than inside the **_"functions.php"_** file. Theme Check plugin reports this as plugin territory. I just thought of sharing this with you. There is no hurry for this though :)

Kind regards,
Manuel

**Comment by marcissimus** [comment]
It's used to enhance the list of contact methods in user profiles. Suffusion adds the following options:

https://github.com/sayontan/suffusion/blob/a0adaadebfa06272b832e628f06862e8087d2892/code/functions/framework.php#L104-L113

Themes shouldn't be doing this but taking it out would be a breaking change since someone might be using it. Let's keep it as is.

**Comment by mbrsolution** [comment]
Thank you Marc for sharing this information. I will make a note of this and close this support thread.

Kind regards,
Manuel
